export const FilterEnum = {
    customer : 0,
    farmingSeason : 1,
    farmRegion : 2,
    fCR : 3,
    fishPond : 4,
    personnel : 5,
    product : 6,
    productGroup : 7,
    productSubgroup : 8,
    productUnit : 9,
    receiptType : 10,
    stockingSection : 11,
    stockIssueDocket : 12,
    stockIssueDocketDetail : 13,
    stockIssueDocketType : 14,
    stockIssueReceipt : 15,
    stockReceiveDocket : 16,
    stockReceiveDocketDetail : 17,
    stockReceiveDocketType : 18,
    stockReceivePaySlip : 19,
    supplier : 20,
    supplierBranch : 21,
    warehouse : 22,
    warehouseType : 23
}