import * as React from "react";

interface IPersonnel {
    code: string;
    compareCode: string;
    firstName: string;
    lastName: string;
    fullName: string;
    gender: number;
    birthday: Date | string | null;
    placeOfBirthId: number | null;
    fatherHometownId: number | null;
    nationalityId: number | null;
    religionId: number | null;
    ethnicId: number | null;
    idNumber: string;
    idIssuePlaceId: number | null;
    idIssueDate: Date | string | null;
    idcNumber: string;
    idcIssuePlaceId: number | null;
    idcIssueDate: Date | string | null;
    majorLevelId: number | null;
    studyLevelId: number | null;
    phone: string;
    hometownAddress: string;
    hometownPrecinctId: number | null;
    hometownDistrictId: number | null;
    hometownProvinceId: number | null;
    currentAddress: string;
    currentPrecinctId: number | null;
    currentDistrictId: number | null;
    currentProvinceId: number | null;
    taxCode: string;
    beginEmployDate: Date | string | null;
    endEmployDate: Date | string | null;
    contractCode: string;
    waterBodyId: number | null;
    positionId: number | null;
    careerTitleId: number | null;
}
export class PersonnelModel implements IPersonnel {
    code: string;
    compareCode: string;
    firstName: string;
    lastName: string;
    fullName: string;
    gender: number;
    birthday: Date | string | null;
    placeOfBirthId: number | null;
    fatherHometownId: number | null;
    nationalityId: number | null;
    religionId: number | null;
    ethnicId: number | null;
    idNumber: string;
    idIssuePlaceId: number | null;
    idIssueDate: Date | string | null;
    idcNumber: string;
    idcIssuePlaceId: number | null;
    idcIssueDate: Date | string | null;
    majorLevelId: number | null;
    studyLevelId: number | null;
    phone: string;
    hometownAddress: string;
    hometownPrecinctId: number | null;
    hometownDistrictId: number | null;
    hometownProvinceId: number | null;
    currentAddress: string;
    currentPrecinctId: number | null;
    currentDistrictId: number | null;
    currentProvinceId: number | null;
    taxCode: string;
    beginEmployDate: Date | string | null;
    endEmployDate: Date | string | null;
    contractCode: string;
    waterBodyId: number | null;
    positionId: number | null;
    careerTitleId: number | null;
}